const VERSION='v39.3 Core + FCM Stable';
const LS='pisl_fieldops_v393';
let current=null, activeView='dashboard', db=null, storage=null, messaging=null, cloudReady=false, deferredPrompt=null, unsubs=[];
let state={users:[],jobs:[],notifications:[],customers:[],sites:[],proposals:[],pushTokens:[],checklistLibrary:{}};
const DEFAULT_USERS=[
{id:'u_admin',username:'sandeep',password:'admin123',name:'Sandeep K',role:'Admin',managerId:null,active:true},
{id:'u_coord',username:'coordinator',password:'coord123',name:'Coordinator',role:'Coordinator',managerId:'u_admin',active:true},
{id:'u_super',username:'supervisor',password:'super123',name:'Supervisor',role:'Supervisor',managerId:'u_admin',active:true},
{id:'u_eng',username:'engineer',password:'eng123',name:'Engineer',role:'Engineer',managerId:'u_super',active:true}
];
const SYSTEMS=['CCTV','Access Control','Fire Alarm','Public Address','Water Leak Detection','Fire Extinguisher','Fire Sprinkler','Fire Hydrant','Emergency Lighting','LED Signage','Network/Structured Cabling','Other'];
const JOB_TYPES=['Service Call','PM Visit','Breakdown','Installation','Inspection','Survey','Quotation Visit','Other'];
const STATUSES=['Assigned','Accepted','Working','Report Draft','Report Shared','Awaiting Closure','Closed'];
const NEXT={Assigned:'Accepted',Accepted:'Working',Working:'Report Draft','Report Draft':'Report Shared','Report Shared':'Awaiting Closure','Awaiting Closure':'Closed'};
const BASE_CHECKLISTS={
'CCTV':{service:['Camera physical condition checked','Camera view/angle verified','Live view confirmed','Recording playback checked','Date/time verified','Client remarks captured'],pm:['Camera cleaning completed','Lens/view checked','Recording retention verified','NVR health/storage checked','Camera naming/date-time checked','Client remarks captured']},
'Access Control':{service:['Door lock condition checked','Reader operation checked','Exit switch/RTE checked','Door sensor status checked','Access event verified','Client remarks captured'],pm:['Reader cleaned and tested','Lock alignment checked','Exit switch tested','Door sensor event checked','Controller communication checked','Client remarks captured']},
'Fire Alarm':{service:['Panel status checked','Detector/MCP condition checked','Hooter/sounder condition checked','Battery/SMPS condition checked','Fault/disablement remarks captured','Client remarks captured'],pm:['Panel healthy condition verified','Detector visual inspection completed','MCP and hooter sample test done','Battery/charger voltage checked','Loop/device fault checked','Client remarks captured']},
'Public Address':{service:['Amplifier/controller status checked','Microphone paging checked','Speaker zone audio checked','Volume/clarity verified','Client remarks captured'],pm:['Amplifier health checked','All-call paging tested','Zone-wise speaker output checked','Microphone condition checked','Rack/cable condition checked','Client remarks captured']},
'Water Leak Detection':{service:['Panel status checked','Sensing cable condition checked','Hooter/relay output checked','Location mapping verified','Client remarks captured'],pm:['Panel healthy status verified','Sensing cable visual check completed','Alarm simulation/sample test done','Hooter/relay output checked','Client remarks captured']},
'Fire Extinguisher':{service:['Cylinder physical condition checked','Pressure/weight checked','Seal/hose/nozzle checked','Expiry/refill due checked','Location tag verified'],pm:['Cylinder location verified','Pressure/weight checked','Seal/hose/nozzle checked','Expiry/refill due updated','Client remarks captured']},
'Fire Sprinkler':{service:['Valve condition checked','Pressure gauge checked','Sprinkler head visual check','Flow/tamper status checked','Client remarks captured'],pm:['Valve position verified','Pressure gauge condition checked','Sprinkler head visual inspection done','Flow/tamper interface checked','Client remarks captured']},
'Fire Hydrant':{service:['Hose reel/hose box condition checked','Valve/nozzle condition checked','Pressure/line condition checked','Pump interface remarks captured'],pm:['Hose reel and hose box inspected','Valve/nozzle condition checked','Pressure/line condition checked','Pump interface remarks captured','Client remarks captured']},
'Emergency Lighting':{service:['Lamp glowing checked','Battery backup checked','Charging indicator checked','Mounting/signage visibility checked'],pm:['Lamp operation checked','Battery backup checked','Charging indicator checked','Mounting/signage visibility checked','Client remarks captured']},
'LED Signage':{service:['LED strip/module checked','Battery backup checked','Charging status checked','Direction visibility checked'],pm:['LED module/strip checked','Battery backup checked','Charging status checked','Direction visibility checked','Client remarks captured']},
'Network/Structured Cabling':{service:['Cable/termination checked','Rack/patching verified','Link status checked','Labeling checked'],pm:['Rack dressing checked','Patch cord/termination checked','Link status verified','Labeling checked','Client remarks captured']},
'Other':{service:['Physical condition checked','Functional test completed','Client remarks captured'],pm:['Physical condition checked','Functional test completed','Client remarks captured']}
};
const $=id=>document.getElementById(id);
const now=()=>new Date().toISOString();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const slug=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,70)||('id_'+Date.now());
function defaults(){ if(!state.users.length)state.users=DEFAULT_USERS; if(!state.customers.length)state.customers=[{name:'PayPal India Pvt Ltd'},{name:'Swiggy'},{name:'Tablespace'},{name:'Clicktech Retail Pvt Ltd'},{name:'Tekion'}]; if(!state.sites.length)state.sites=[{customerName:'PayPal India Pvt Ltd',name:'Bangalore'},{customerName:'Swiggy',name:'ETV / Sumadhura Capital'},{customerName:'Tablespace',name:'TST2 Camellia Whitefield'}]; if(!state.checklistLibrary||!Object.keys(state.checklistLibrary).length)state.checklistLibrary=BASE_CHECKLISTS; }
function loadLocal(){try{let c=JSON.parse(localStorage.getItem(LS)||'{}');state={...state,...c}}catch(e){} defaults(); saveLocal(); initFirebase();}
function saveLocal(){localStorage.setItem(LS,JSON.stringify(state));}
async function initFirebase(){try{if(window.firebaseConfig&&firebase?.apps?.length===0)firebase.initializeApp(firebaseConfig); if(firebase?.apps?.length){db=firebase.firestore(); storage=firebase.storage?.(); messaging=firebase.messaging?.isSupported? await firebase.messaging.isSupported().then(ok=>ok?firebase.messaging():null):null; cloudReady=true; try{await firebase.auth().signInAnonymously()}catch(e){console.warn('Auth skipped',e)} }}catch(e){console.warn('Firebase offline/local mode',e);cloudReady=false}}
function login(){let u=$('u').value.trim().toLowerCase(),p=$('p').value;let user=state.users.find(x=>x.active!==false&&x.username.toLowerCase()===u&&x.password===p); if(!user){$('loginMsg').textContent='Invalid username or password';return} current=user; $('login').classList.add('hidden'); $('app').classList.remove('hidden'); $('who').textContent=current.name; $('role').textContent=current.role; buildNav(); go('dashboard'); startRealtime();}
function logout(){unsubs.forEach(x=>{try{x()}catch(e){}});unsubs=[];current=null;$('app').classList.add('hidden');$('login').classList.remove('hidden')}
function navItems(){let base=['Dashboard','Jobs','Create Job','Masters','Notifications','Proposal / Quotation']; if(current?.role==='Admin')base.push('Administration'); return base}
function key(x){return x.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
function buildNav(){ $('nav').innerHTML=navItems().map(x=>`<button class="${activeView===key(x)?'active':''}" onclick="go('${key(x)}')">${x}</button>`).join('')}
function go(v){activeView=v;toggleMenu(false);buildNav();render()}
function toggleMenu(open){$('side')?.classList.toggle('open',open??!$('side').classList.contains('open')); $('drawerBackdrop')?.classList.toggle('show',$('side')?.classList.contains('open'))}
function setTitle(t,sub=VERSION){$('pageTitle').textContent=t;$('pageSubtitle').textContent=sub}
function render(){let el=$('view'); if(!current)return; ({dashboard:renderDashboard,jobs:renderJobs,create_job:renderCreate,masters:renderMasters,notifications:renderNotifications,proposal_quotation:renderProposal,administration:renderAdmin}[activeView]||renderDashboard)(el)}
function visibleJobs(){if(current.role==='Engineer')return state.jobs.filter(j=>j.assignedToId===current.id||j.visibleTo?.includes(current.id)); return state.jobs}
function renderDashboard(el){setTitle('Dashboard');let jobs=visibleJobs(),open=jobs.filter(j=>j.status!=='Closed'),today=new Date().toISOString().slice(0,10);el.innerHTML=`<div class="grid"><div class="card stat"><span class="muted">Total Jobs</span><h2>${jobs.length}</h2></div><div class="card stat"><span class="muted">Open Jobs</span><h2>${open.length}</h2></div><div class="card stat"><span class="muted">Closed</span><h2>${jobs.filter(j=>j.status==='Closed').length}</h2></div><div class="card stat"><span class="muted">Today</span><h2>${jobs.filter(j=>(j.createdAt||'').slice(0,10)===today).length}</h2></div></div><div class="card"><h3>Recent Jobs</h3>${jobTable(jobs.slice(0,8))}</div>`}
function statusPill(s){let c=s==='Closed'?'ok':s==='Assigned'?'warn':s==='Awaiting Closure'?'bad':'';return `<span class="pill ${c}">${esc(s||'Assigned')}</span>`}
function jobTable(jobs){return `<div class="tablewrap"><table><thead><tr><th>Ticket</th><th>Customer / Site</th><th>Type</th><th>Systems</th><th>Status</th><th>Engineer</th><th>Action</th></tr></thead><tbody>${jobs.map(j=>`<tr><td><b>${esc(j.ticketId||'NO-TICKET')}</b><br><span class="muted">${esc((j.createdAt||'').replace('T',' ').slice(0,16))}</span></td><td>${esc(j.customerName)}<br><span class="muted">${esc(j.siteName)}</span></td><td>${esc(j.type||'Service Call')}</td><td>${(j.systems||[]).map(s=>`<span class="pill">${esc(s)}</span>`).join('')}</td><td>${statusPill(j.status)}</td><td>${esc(j.assignedToName)}</td><td><button class="btn small" onclick="openJob('${esc(j.firestoreId||j.ticketId)}')">Open</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">No jobs found.</td></tr>'}</tbody></table></div>`}
function renderJobs(el){setTitle('Jobs');let q=(window.jobSearch||'').toLowerCase(),f=window.jobFilter||'All';let jobs=visibleJobs().filter(j=>(f==='All'||j.status===f)&&JSON.stringify(j).toLowerCase().includes(q));el.innerHTML=`<div class="card"><div class="grid three"><div><label>Search</label><input id="search" placeholder="Ticket, customer, site, engineer" value="${esc(window.jobSearch||'')}" oninput="window.jobSearch=this.value;render()"></div><div><label>Status Filter</label><select onchange="window.jobFilter=this.value;render()"><option>All</option>${STATUSES.map(s=>`<option ${f===s?'selected':''}>${s}</option>`).join('')}</select></div><div><label>&nbsp;</label><button class="btn" onclick="go('create_job')">+ Create Job</button></div></div></div>${jobTable(jobs)}`}
function newTicket(prefix='SRV'){let d=new Date(),ymd=d.toISOString().slice(0,10).replace(/-/g,''),tail=String(Date.now()).slice(-5);return `${prefix}-${ymd}-${tail}`}
function buildVisibleTo(eng){let arr=[eng,current.id,'u_admin'];let u=state.users.find(x=>x.id===eng); if(u?.managerId)arr.push(u.managerId); return [...new Set(arr)]}
function renderCreate(el){setTitle('Create Job');let eng=state.users.filter(u=>['Engineer','Supervisor','Admin','Coordinator'].includes(u.role)).map(u=>`<option value="${u.id}">${esc(u.name)} - ${esc(u.role)}</option>`).join('');let cust=state.customers.map(c=>`<option value="${esc(c.name)}">`).join(''),sites=state.sites.map(s=>`<option value="${esc(s.name)}">`).join('');el.innerHTML=`<div class="card"><h3>New Job</h3><div class="grid two"><div><label>Customer</label><input id="cj_customer" list="customersList"><datalist id="customersList">${cust}</datalist></div><div><label>Site</label><input id="cj_site" list="sitesList"><datalist id="sitesList">${sites}</datalist></div></div><div class="grid two"><div><label>Job Type</label><select id="cj_type">${JOB_TYPES.map(t=>`<option>${t}</option>`).join('')}</select></div><div><label>Assign To</label><select id="cj_eng">${eng}</select></div></div><label>Systems</label><div class="grid three">${SYSTEMS.map(s=>`<label class="check"><input type="checkbox" class="sys" value="${esc(s)}"> ${esc(s)}</label>`).join('')}</div><label>Scope / Complaint</label><textarea id="cj_scope" placeholder="Enter work scope, complaint or PM visit details"></textarea><button class="btn ok" onclick="createJob()">Create & Assign Job</button></div>`}
function checklistFor(type,systems){let mode=(type==='PM Visit')?'pm':'service'; let rows=[]; (systems&&systems.length?systems:['Other']).forEach(s=>{let t=state.checklistLibrary?.[s]||BASE_CHECKLISTS[s]||BASE_CHECKLISTS.Other; (t[mode]||t.service||[]).forEach(item=>rows.push({system:s,item,done:false,remarks:''}))}); return rows;}
async function createJob(){let customerName=$('cj_customer').value.trim(),siteName=$('cj_site').value.trim(),type=$('cj_type').value,assignedToId=$('cj_eng').value,systems=[...document.querySelectorAll('.sys:checked')].map(x=>x.value),scope=$('cj_scope').value.trim(); if(!customerName||!siteName||!assignedToId||!scope){alert('Please fill Customer, Site, Engineer and Scope.');return} let assigned=state.users.find(u=>u.id===assignedToId)||{}; let job={ticketId:newTicket(type==='PM Visit'?'PM':'SRV'),customerName,siteName,type,systems:systems.length?systems:['Other'],scope,status:'Assigned',assignedToId,assignedToName:assigned.name||'',createdBy:current.id,createdByName:current.name,createdAt:now(),updatedAt:now(),visibleTo:buildVisibleTo(assignedToId),checklist:checklistFor(type,systems),photos:[],workNotes:'',customerRemarks:''}; state.jobs.unshift(job); saveLocal(); if(cloudReady){try{let ref=await db.collection('jobs').add(job);job.firestoreId=ref.id;await ref.set(job,{merge:true});saveLocal()}catch(e){console.warn(e)}} await notify(job,`New job assigned: ${job.ticketId} - ${job.customerName}`); alert('Job created: '+job.ticketId); go('jobs')}
function findJob(id){return state.jobs.find(j=>j.firestoreId===id||j.ticketId===id)}
function openJob(id){let j=findJob(id); if(!j)return alert('Job not found'); setTitle(j.ticketId||'Job Detail',`${j.customerName} / ${j.siteName}`); let next=NEXT[j.status]; let photoHtml=(j.photos||[]).map((p,i)=>`<div class="photoBox"><img src="${p.dataUrl}"><b>${esc(p.fileName||('Photo '+(i+1)))}</b><br><button class="btn small bad" onclick="removePhoto('${id}',${i})">Remove</button></div>`).join('')||'<p class="muted">No photos uploaded.</p>';$('view').innerHTML=`<div class="card"><div class="grid two"><div class="kv"><b>Ticket</b><span>${esc(j.ticketId)}</span><b>Customer</b><span>${esc(j.customerName)}</span><b>Site</b><span>${esc(j.siteName)}</span><b>Type</b><span>${esc(j.type)}</span><b>Status</b><span>${statusPill(j.status)}</span><b>Engineer</b><span>${esc(j.assignedToName)}</span></div><div><h3>Scope</h3><p>${esc(j.scope)}</p><div class="actions">${next?`<button class="btn ok" onclick="advanceJob('${id}')">Move to ${next}</button>`:''}<button class="btn" onclick="printReport('${id}')">Report PDF / Print</button><button class="btn secondary" onclick="shareWhatsApp('${id}')">WhatsApp</button><button class="btn secondary" onclick="shareEmail('${id}')">Email</button><button class="btn bad" onclick="deleteJob('${id}')">Delete</button></div></div></div></div><div class="card"><h3>Work Notes</h3><textarea id="workNotes">${esc(j.workNotes||'')}</textarea><label>Customer Remarks</label><textarea id="custRemarks">${esc(j.customerRemarks||'')}</textarea><button class="btn" onclick="saveJobNotes('${id}')">Save Notes</button></div><div class="card"><h3>Checklist</h3>${(j.checklist||[]).map((c,i)=>`<label class="check"><input type="checkbox" ${c.done?'checked':''} onchange="toggleCheck('${id}',${i},this.checked)"><b>${esc(c.system)}</b> - ${esc(c.item)}</label>`).join('')||'<p class="muted">No checklist items.</p>'}</div><div class="card"><h3>Photo Evidence</h3><input type="file" accept="image/*" multiple onchange="previewAndAddPhotos('${id}',this)"><div id="preview" class="preview"></div><div class="photoGrid">${photoHtml}</div></div>`}
function saveJobNotes(id){let j=findJob(id);j.workNotes=$('workNotes').value;j.customerRemarks=$('custRemarks').value;j.updatedAt=now();saveJob(j);openJob(id)}
function toggleCheck(id,i,val){let j=findJob(id); if(j?.checklist?.[i]){j.checklist[i].done=val;j.updatedAt=now();saveJob(j)}}
function previewAndAddPhotos(id,input){let files=[...input.files]; if(!files.length)return; let preview=$('preview');preview.innerHTML=`<p><b>${files.length}</b> photo(s) selected. Loading preview...</p>`;let done=0;files.forEach(f=>{let r=new FileReader();r.onload=e=>{let j=findJob(id);j.photos=j.photos||[];j.photos.push({fileName:f.name,dataUrl:e.target.result,createdAt:now()});done++; if(done===files.length){saveJob(j);openJob(id)}};r.readAsDataURL(f)})}
function removePhoto(id,i){let j=findJob(id);j.photos.splice(i,1);saveJob(j);openJob(id)}
function advanceJob(id){let j=findJob(id); if(NEXT[j.status]){j.status=NEXT[j.status];j.updatedAt=now();saveJob(j);notify(j,`${j.ticketId} moved to ${j.status}`);openJob(id)}}
function deleteJob(id){if(!confirm('Delete this job?'))return;let j=findJob(id);state.jobs=state.jobs.filter(x=>x!==j);saveLocal(); if(cloudReady&&j.firestoreId)db.collection('jobs').doc(j.firestoreId).delete().catch(console.warn);go('jobs')}
async function saveJob(j){saveLocal(); if(cloudReady&&j.firestoreId)try{await db.collection('jobs').doc(j.firestoreId).set(j,{merge:true})}catch(e){console.warn(e)}}
function reportHtml(j){let ck=(j.checklist||[]).map(c=>`<tr><td>${esc(c.system)}</td><td>${esc(c.item)}</td><td>${c.done?'Completed':'Pending'}</td></tr>`).join('');let photos=(j.photos||[]).map(p=>`<div class="photoBox"><img src="${p.dataUrl}"><b>${esc(p.fileName)}</b></div>`).join('');return `<div class="reportPaper"><div class="reportHead"><div><h1>Field Service Report</h1><b>Payaswini Integrated Solutions</b><p>PISL FieldOps Report</p></div><img src="${new URL('assets/logo.png',location.href).href}"></div><div class="kv"><b>Ticket</b><span>${esc(j.ticketId)}</span><b>Date</b><span>${esc((j.createdAt||'').replace('T',' ').slice(0,16))}</span><b>Customer</b><span>${esc(j.customerName)}</span><b>Site</b><span>${esc(j.siteName)}</span><b>Job Type</b><span>${esc(j.type)}</span><b>Status</b><span>${esc(j.status)}</span><b>Engineer</b><span>${esc(j.assignedToName)}</span><b>Scope</b><span>${esc(j.scope)}</span><b>Work Notes</b><span>${esc(j.workNotes||'')}</span><b>Customer Remarks</b><span>${esc(j.customerRemarks||'')}</span></div><h3>Checklist</h3><table><thead><tr><th>System</th><th>Activity</th><th>Status</th></tr></thead><tbody>${ck||'<tr><td colspan="3">No checklist</td></tr>'}</tbody></table><h3>Photo Evidence</h3><div class="photoGrid">${photos||'<p>No photos attached.</p>'}</div><div class="signrow"><div class="sig">Engineer Signature</div><div class="sig">Client Signature</div></div></div>`}
function printReport(id){let j=findJob(id);let w=window.open('','_blank');w.document.write(`<!doctype html><html><head><title>${esc(j.ticketId)}</title><link rel="stylesheet" href="${new URL('css/main.css',location.href).href}"></head><body>${reportHtml(j)}<script>setTimeout(()=>print(),500)<\/script></body></html>`);w.document.close()}
function shareWhatsApp(id){let j=findJob(id);let txt=`${j.ticketId} - ${j.customerName} / ${j.siteName}\nType: ${j.type}\nStatus: ${j.status}\nEngineer: ${j.assignedToName}`;window.open('https://wa.me/?text='+encodeURIComponent(txt),'_blank')}
function shareEmail(id){let j=findJob(id);let sub=`Service Report ${j.ticketId}`;let body=`Dear Team,\n\nPlease find the service update below.\n\nTicket: ${j.ticketId}\nCustomer: ${j.customerName}\nSite: ${j.siteName}\nType: ${j.type}\nStatus: ${j.status}\nEngineer: ${j.assignedToName}\n\nRegards,\nPayaswini Integrated Solutions`;location.href=`mailto:?subject=${encodeURIComponent(sub)}&body=${encodeURIComponent(body)}`}
function renderMasters(el){setTitle('Masters');el.innerHTML=`<div class="tabs"><button class="btn tab active">Customer / Site</button><button class="btn tab">Engineer</button><button class="btn tab">Checklist Library</button></div><div class="grid two"><div class="card"><h3>Customer Master</h3><input id="m_customer" placeholder="Customer name"><button class="btn" onclick="addCustomer()">Add Customer</button>${state.customers.map(c=>`<p>• ${esc(c.name)}</p>`).join('')}</div><div class="card"><h3>Site Master</h3><input id="m_site_customer" placeholder="Customer name"><input id="m_site" placeholder="Site name"><button class="btn" onclick="addSite()">Add Site</button>${state.sites.map(s=>`<p>• ${esc(s.customerName)} - ${esc(s.name)}</p>`).join('')}</div><div class="card"><h3>Engineer Master</h3>${state.users.map(u=>`<p>• ${esc(u.name)} - ${esc(u.role)} (${esc(u.username)})</p>`).join('')}</div><div class="card"><h3>Default System-wise Checklist Library</h3>${Object.keys(state.checklistLibrary).map(s=>`<details><summary><b>${esc(s)}</b></summary><p><b>Service:</b></p><ol>${(state.checklistLibrary[s].service||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p><b>PM:</b></p><ol>${(state.checklistLibrary[s].pm||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></details>`).join('')}</div></div>`}
function addCustomer(){let name=$('m_customer').value.trim();if(name&&!state.customers.some(c=>c.name.toLowerCase()===name.toLowerCase()))state.customers.push({name});saveLocal();render()}
function addSite(){let customerName=$('m_site_customer').value.trim(),name=$('m_site').value.trim();if(customerName&&name)state.sites.push({customerName,name});saveLocal();render()}
function renderNotifications(el){setTitle('Notifications');let ns=state.notifications.filter(n=>!n.toIds||n.toIds.includes(current.id)||current.role==='Admin');el.innerHTML=`<div class="card"><h3>Notification Center</h3>${ns.map(n=>`<div class="card"><b>${esc(n.title)}</b><p>${esc(n.message)}</p><span class="muted">${esc((n.createdAt||'').replace('T',' ').slice(0,16))}</span></div>`).join('')||'<p class="muted">No notifications.</p>'}</div>`}
function renderProposal(el){setTitle('Proposal / Quotation');el.innerHTML=`<div class="card"><h3>Create Proposal / Quotation</h3><div class="grid two"><div><label>Customer</label><input id="pr_customer" list="customersList2"><datalist id="customersList2">${state.customers.map(c=>`<option value="${esc(c.name)}">`).join('')}</datalist></div><div><label>Site</label><input id="pr_site"></div></div><div class="grid two"><div><label>Subject</label><input id="pr_subject" placeholder="NCAMC / Service / Supply quotation"></div><div><label>Reference No.</label><input id="pr_ref" value="PISL/QUO/${new Date().getFullYear()}-${String(new Date().getFullYear()+1).slice(-2)}/${String(Date.now()).slice(-3)}"></div></div><label>Commercial Lines (one per line: Description | Qty | Rate)</label><textarea id="pr_lines" placeholder="CCTV PM Service | 1 | 5000"></textarea><button class="btn ok" onclick="makeProposal()">Generate Proposal Preview</button></div><div id="proposalOut"></div>`}
function makeProposal(){let c=$('pr_customer').value,s=$('pr_site').value,sub=$('pr_subject').value,ref=$('pr_ref').value,lines=$('pr_lines').value.split('\n').filter(Boolean).map((l,i)=>{let p=l.split('|').map(x=>x.trim());let q=Number(p[1]||0),r=Number(p[2]||0);return {i:i+1,desc:p[0]||l,qty:p[1]||'',rate:p[2]||'',amt:q&&r?q*r:''}});let total=lines.reduce((a,b)=>a+(Number(b.amt)||0),0);$('proposalOut').innerHTML=`<div class="reportPaper"><div class="reportHead"><div><h1>Proposal / Quotation</h1><b>Payaswini Integrated Solutions</b><p>Ref: ${esc(ref)} &nbsp; Date: ${new Date().toLocaleDateString()}</p></div><img src="assets/logo.png"></div><div class="kv"><b>Customer</b><span>${esc(c)}</span><b>Site</b><span>${esc(s)}</span><b>Subject</b><span>${esc(sub)}</span></div><h3>Commercial Offer</h3><table class="proposalTable"><thead><tr><th>Sr</th><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${lines.map(x=>`<tr><td>${x.i}</td><td>${esc(x.desc)}</td><td>${esc(x.qty)}</td><td>${esc(x.rate)}</td><td>${esc(x.amt)}</td></tr>`).join('')}<tr><th colspan="4">Total</th><th>${esc(total||'')}</th></tr></tbody></table><h3>Terms & Conditions</h3><p>Taxes extra as applicable. Validity 30 days. Payment as mutually agreed. Scope limited to the above mentioned systems/items only.</p><div class="signrow"><div class="sig">For Payaswini Integrated Solutions</div><div class="sig">Client Acceptance</div></div><button class="btn noPrint" onclick="window.print()">Print / Save PDF</button></div>`}
function renderAdmin(el){setTitle('Administration');el.innerHTML=`<div class="grid two"><div class="card"><h3>FCM Push Alerts</h3><p class="muted">VAPID key is now handled from <b>js/firebase-config.js</b>. It is no longer shown on screen.</p><button class="btn ok" onclick="enableFCM()">Enable FCM Alerts on This Device</button></div><div class="card"><h3>Maintenance</h3><button class="btn secondary" onclick="backupJson()">Backup JSON</button><button class="btn warn" onclick="state.notifications=[];saveLocal();render()">Clear Local Notifications</button></div><div class="card"><h3>Build Scope</h3><p>Included: Jobs, realtime updates, FCM token registration, system-wise checklists, job-specific checklists, service reports, photo upload, WhatsApp/email sharing, masters, proposal creation.</p><p>Excluded: Attendance, GPS, QR, SLA, asset history.</p></div></div>`}
async function enableFCM(){try{if(!messaging){alert('FCM not supported in this browser or Firebase not ready.');return}let vapid=(window.FCM_PUBLIC_VAPID_KEY||'').trim(); if(!vapid){alert('FCM VAPID key is not configured in js/firebase-config.js.');return}let perm=await Notification.requestPermission(); if(perm!=='granted'){alert('Notification permission not granted.');return}let token=await messaging.getToken({vapidKey:vapid});state.pushTokens=state.pushTokens.filter(t=>t.token!==token);state.pushTokens.push({token,userId:current.id,name:current.name,createdAt:now()});saveLocal(); if(cloudReady)await db.collection('pushTokens').doc(current.id+'_'+slug(token.slice(-12))).set({token,userId:current.id,name:current.name,role:current.role,updatedAt:now()},{merge:true});alert('FCM enabled for this device.')}catch(e){console.error(e);alert('FCM enable failed. Check HTTPS, Firebase config, and VAPID key.')}}
async function notify(j,msg){let n={title:'FieldOps',message:msg,toIds:j.visibleTo||[],ticketId:j.ticketId,createdAt:now(),read:false};state.notifications.unshift(n);saveLocal(); if(cloudReady)try{await db.collection('notifications').add(n)}catch(e){}}
function backupJson(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='pisl-fieldops-backup.json';a.click()}
function startRealtime(){if(!cloudReady)return;unsubs.forEach(u=>u());unsubs=[];try{unsubs.push(db.collection('jobs').orderBy('createdAt','desc').limit(200).onSnapshot(s=>{let remote=s.docs.map(d=>({firestoreId:d.id,...d.data()}));remote.forEach(r=>{let i=state.jobs.findIndex(j=>j.firestoreId===r.firestoreId); if(i>=0)state.jobs[i]=r; else state.jobs.unshift(r)});saveLocal(); if(!$('login').classList.contains('hidden'))return; render();}));unsubs.push(db.collection('notifications').orderBy('createdAt','desc').limit(100).onSnapshot(s=>{state.notifications=s.docs.map(d=>({firestoreId:d.id,...d.data()}));saveLocal(); if(activeView==='notifications')render()}))}catch(e){console.warn('Realtime not available',e)}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn')?.classList.remove('hidden')});
function installPWA(){if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('installBtn').classList.add('hidden')}else alert('Use browser menu → Install app / Add to Home Screen')}
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(console.warn);
window.onload=loadLocal;
