const VERSION='v39.1 Core FieldOps + FCM';
const LS='pisl_v39_1_cache';
const FCM_KEY_LS='pisl_fcm_vapid_key';
let current=null, activeView='dashboard', db=null, storage=null, messaging=null, cloudReady=false, unsubscribers=[], deferredPrompt=null;
let state={users:[],jobs:[],notifications:[],customers:[],sites:[],proposals:[],pushTokens:[]};

const DEFAULT_USERS=[
 {id:'u_admin',username:'sandeep',password:'admin123',name:'Sandeep K',role:'Admin',managerId:null,active:true},
 {id:'u_coord',username:'coordinator',password:'coord123',name:'Coordinator',role:'Coordinator',managerId:'u_admin',active:true},
 {id:'u_super',username:'supervisor',password:'super123',name:'Supervisor',role:'Supervisor',managerId:'u_admin',active:true},
 {id:'u_eng',username:'engineer',password:'eng123',name:'Engineer',role:'Engineer',managerId:'u_super',active:true},
 {id:'u_view',username:'viewer',password:'view123',name:'Viewer',role:'Viewer',managerId:'u_admin',active:true}
];
const SYSTEMS=['CCTV','Access Control','Fire Alarm','Public Address','Water Leak Detection','Fire Extinguisher','Fire Sprinkler','Fire Hydrant','Emergency Lighting','LED Signage','Network/Structured Cabling','Other'];
const JOB_TYPES=['Service Call','PM Visit','Breakdown','Installation','Inspection','Survey','Quotation Visit','Other'];
const STATUSES=['Assigned','Accepted','Working','Report Draft','Report Shared','Awaiting Closure','Closed'];
const NEXT_STATUS={Assigned:'Accepted',Accepted:'Working',Working:'Report Draft','Report Draft':'Report Shared','Report Shared':'Awaiting Closure','Awaiting Closure':'Closed'};
const CHECKLIST_TEMPLATES={
 'CCTV':['Camera physical condition verified','Camera view/angle checked','Live view confirmed','Recording playback checked','Date/time verified','Remarks captured'],
 'Access Control':['Door lock condition checked','Reader operation checked','Exit switch/RTE checked','Door sensor status checked','Access event verified','Remarks captured'],
 'Fire Alarm':['Panel status normal/fault checked','Detector/MCP zone condition checked','Hooter/sounder condition checked','Battery/SMPS condition checked','Loop/device remarks captured'],
 'Public Address':['Amplifier/controller status checked','Microphone/paging checked','Speaker zone audio checked','Volume/clarity checked','Remarks captured'],
 'Water Leak Detection':['Panel status checked','Sensing cable condition checked','Hooter/relay output checked','Location mapping verified','Remarks captured'],
 'Fire Extinguisher':['Cylinder condition checked','Pressure/weight checked','Seal/hose/nozzle checked','Expiry/refill due checked','Location tag verified'],
 'Fire Sprinkler':['Valve condition checked','Pressure gauge checked','Sprinkler head visual check','Flow/tamper status checked','Remarks captured'],
 'Fire Hydrant':['Hose reel/hose box condition checked','Valve/nozzle condition checked','Pressure/line condition checked','Pump interface remarks captured'],
 'Emergency Lighting':['Lamp glowing checked','Battery backup checked','Charging indicator checked','Mounting/signage visibility checked'],
 'LED Signage':['LED strip/module checked','Battery backup checked','Charging status checked','Direction visibility checked'],
 'Network/Structured Cabling':['Cable/termination checked','Rack/patching verified','Link status checked','Labeling checked'],
 'Other':['Physical condition checked','Functional test completed','Client remarks captured']
};
function $(id){return document.getElementById(id)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function slug(s){return String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||'item'}
function now(){return new Date().toISOString()}
function newTicket(prefix='PISL'){const d=new Date();const ymd=d.toISOString().slice(0,10).replaceAll('-','');return `${prefix}-${ymd}-${String(d.getTime()).slice(-5)}`}
function loadLocal(){try{let s=JSON.parse(localStorage.getItem(LS)); if(s)state={...state,...s}}catch(e){}; if(!state.users?.length)state.users=DEFAULT_USERS.slice()}
function saveLocal(){try{localStorage.setItem(LS,JSON.stringify(state))}catch(e){console.warn('Local cache full',e)}}
function initFirebase(){try{if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);db=firebase.firestore();storage=firebase.storage();if(firebase.messaging&&location.protocol==='https:')messaging=firebase.messaging();cloudReady=true;}catch(e){console.warn('Firebase unavailable',e);cloudReady=false}}
async function ensureSeed(){if(!cloudReady)return;const s=await db.collection('users').limit(1).get();if(s.empty){for(const u of DEFAULT_USERS) await db.collection('users').doc(u.id).set(u,{merge:true})}}
async function pullUsers(){if(!cloudReady)return;const s=await db.collection('users').get();state.users=s.docs.map(d=>({id:d.id,...d.data()}));saveLocal()}
async function login(){loadLocal();initFirebase();let un=$('u').value.trim().toLowerCase(), pw=$('p').value.trim();try{if(cloudReady){await firebase.auth().signInAnonymously();await ensureSeed();await pullUsers();}}catch(e){console.warn(e)}const u=state.users.find(x=>x.username?.toLowerCase()===un&&x.password===pw&&x.active!==false);if(!u){$('loginMsg').textContent='Invalid username or password';return}current=u;$('login').classList.add('hidden');$('app').classList.remove('hidden');$('who').textContent=u.name;$('role').textContent=u.role;buildNav();startRealtime();go('dashboard')}
function logout(){unsubscribers.forEach(f=>f&&f());unsubscribers=[];current=null;$('app').classList.add('hidden');$('login').classList.remove('hidden')}
function isAdmin(){return current?.role==='Admin'}
function can(v){if(!current)return false;if(isAdmin())return true;if(v==='admin')return false;if(v==='proposal')return ['Coordinator','Supervisor'].includes(current.role);if(v==='create')return current.role!=='Viewer';return true}
function buildNav(){let items=[['dashboard','Dashboard'],['jobs','Jobs'],['create','Create Job'],['masters','Masters'],['notifications','Notifications']];if(can('proposal'))items.push(['proposal','Proposal / Quotation']);if(can('admin'))items.push(['admin','Administration']);$('nav').innerHTML=items.filter(i=>can(i[0])||i[0]==='masters').map(i=>`<button class="${activeView===i[0]?'active':''}" onclick="go('${i[0]}')">${i[1]}</button>`).join('')}
function toggleMenu(){$('side').classList.toggle('open');$('drawerBackdrop').classList.toggle('show')}
function go(v){activeView=v;buildNav();$('side').classList.remove('open');$('drawerBackdrop').classList.remove('show');render()}
function setTitle(t,s=VERSION){$('pageTitle').textContent=t;$('pageSubtitle').textContent=s}
function visibleJobs(){if(!current)return[]; if(current.role==='Engineer')return state.jobs.filter(j=>(j.visibleTo||[]).includes(current.id)||j.assignedToId===current.id);return state.jobs}
function buildVisibleTo(assignedId){let ids=[assignedId,current.id,'u_admin'];let ass=state.users.find(u=>u.id===assignedId);if(ass?.managerId)ids.push(ass.managerId);state.users.filter(u=>['Admin','Coordinator','Supervisor'].includes(u.role)).forEach(u=>ids.push(u.id));return [...new Set(ids.filter(Boolean))]}
function statusClass(st){return st==='Closed'?'ok':st==='Awaiting Closure'?'warn':st==='Working'?'bad':'warn'}

function startRealtime(){if(!cloudReady)return;unsubscribers.forEach(f=>f&&f());unsubscribers=[];let jq=db.collection('jobs').orderBy('createdAt','desc').limit(200);if(current.role==='Engineer')jq=db.collection('jobs').where('visibleTo','array-contains',current.id).orderBy('createdAt','desc').limit(200);unsubscribers.push(jq.onSnapshot(s=>{state.jobs=s.docs.map(d=>({firestoreId:d.id,...d.data()}));saveLocal();if(['dashboard','jobs'].includes(activeView))render();}));unsubscribers.push(db.collection('notifications').where('toIds','array-contains',current.id).orderBy('createdAt','desc').limit(100).onSnapshot(s=>{let old=state.notifications.filter(n=>!n.read).length;state.notifications=s.docs.map(d=>({firestoreId:d.id,...d.data()}));saveLocal();if(state.notifications.filter(n=>!n.read).length>old)notifyPopup();if(['notifications','dashboard'].includes(activeView))render();}));for(const col of ['customers','sites','proposals'])unsubscribers.push(db.collection(col).limit(250).onSnapshot(s=>{state[col]=s.docs.map(d=>({firestoreId:d.id,...d.data()}));saveLocal();if(['masters','create','proposal','dashboard'].includes(activeView))render();}));}
function notifyPopup(){let n=state.notifications.find(x=>!x.read);if(!n)return;if('Notification'in window&&Notification.permission==='granted')new Notification(n.title||'PISL FieldOps',{body:n.message||'New update',icon:'logo.png'});if(navigator.vibrate)navigator.vibrate([180,80,180])}
async function enableFCM(){try{if(!cloudReady){alert('Firebase not connected.');return}if(!('serviceWorker'in navigator)||!messaging){alert('FCM requires HTTPS hosting and browser support.');return}let vapid=localStorage.getItem(FCM_KEY_LS)||'';if(!vapid){vapid=prompt('Paste Firebase Web Push Certificate public VAPID key. This is one-time and saved in this browser.');if(!vapid)return;localStorage.setItem(FCM_KEY_LS,vapid.trim())}let perm=await Notification.requestPermission();if(perm!=='granted'){alert('Notification permission denied.');return}let reg=await navigator.serviceWorker.register('firebase-messaging-sw.js');let token=await messaging.getToken({vapidKey:vapid,serviceWorkerRegistration:reg});if(!token){alert('FCM token not generated.');return}let doc={token,userId:current.id,userName:current.name,role:current.role,userAgent:navigator.userAgent,updatedAt:now(),active:true};await db.collection('pushTokens').doc(current.id+'_'+token.slice(-16)).set(doc,{merge:true});await db.collection('users').doc(current.id).set({fcmEnabled:true,updatedAt:now()},{merge:true});alert('FCM alerts enabled for this device.');}catch(e){console.error(e);alert('FCM setup failed: '+(e.message||e))}}
if(firebase?.messaging){try{setTimeout(()=>{if(messaging)messaging.onMessage(payload=>{let title=payload.notification?.title||'PISL FieldOps';let body=payload.notification?.body||'New job update';if(Notification.permission==='granted')new Notification(title,{body,icon:'logo.png'});})},1000)}catch(e){}}

function render(){const el=$('view');if(activeView==='dashboard')renderDashboard(el);if(activeView==='jobs')renderJobs(el);if(activeView==='create')renderCreate(el);if(activeView==='masters')renderMasters(el);if(activeView==='notifications')renderNotifications(el);if(activeView==='proposal')renderProposal(el);if(activeView==='admin')renderAdmin(el)}
function countJobs(fn){return visibleJobs().filter(fn).length}
function renderDashboard(el){setTitle('Dashboard');let unread=state.notifications.filter(n=>!n.read).length;let today=new Date().toISOString().slice(0,10);let cards=[['Today Jobs',countJobs(j=>(j.createdAt||'').slice(0,10)===today)],['Open Jobs',countJobs(j=>j.status!=='Closed')],['Assigned',countJobs(j=>j.status==='Assigned')],['Working',countJobs(j=>j.status==='Working')],['PM Visits',countJobs(j=>j.type==='PM Visit'&&j.status!=='Closed')],['Service Calls',countJobs(j=>j.type==='Service Call'&&j.status!=='Closed')],['Pending Closure',countJobs(j=>j.status==='Awaiting Closure')],['Unread Alerts',unread]];el.innerHTML=`<div class="grid">${cards.map(c=>`<div class="card stat" onclick="go('${c[0].includes('Alert')?'notifications':'jobs'}')"><span class="muted">${c[0]}</span><h2>${c[1]}</h2></div>`).join('')}</div><div class="card"><h3>Recent Jobs</h3>${jobTable(visibleJobs().slice(0,10))}</div>`}
function filteredJobs(){let list=visibleJobs();let q=($('jobSearch')?.value||'').toLowerCase();let st=$('jobStatus')?.value||'All';let tp=$('jobTypeFilter')?.value||'All';if(q)list=list.filter(j=>[j.ticketId,j.customerName,j.siteName,j.assignedToName,j.type,(j.systems||[]).join(' ')].join(' ').toLowerCase().includes(q));if(st!=='All')list=list.filter(j=>j.status===st);if(tp!=='All')list=list.filter(j=>j.type===tp);return list}
function jobTable(list){if(!list.length)return'<p class="muted">No jobs found.</p>';return`<div class="tablewrap"><table><thead><tr><th>Ticket</th><th>Customer / Site</th><th>Type / System</th><th>Status</th><th>Assigned</th><th>Action</th></tr></thead><tbody>${list.map(j=>`<tr><td><b>${esc(j.ticketId||'Ticket Pending')}</b><br><span class="muted">${esc((j.createdAt||'').slice(0,10))}</span></td><td>${esc(j.customerName)}<br><span class="muted">${esc(j.siteName)}</span></td><td>${esc(j.type||'Service Call')}<br>${(j.systems?.length?j.systems:['Other']).map(s=>`<span class="pill">${esc(s)}</span>`).join('')}</td><td><span class="pill ${statusClass(j.status)}">${esc(j.status||'Assigned')}</span></td><td>${esc(j.assignedToName||'')}</td><td><button class="btn secondary" onclick="openJob('${j.firestoreId||j.ticketId}')">Open</button></td></tr>`).join('')}</tbody></table></div>`}
function renderJobs(el){setTitle('Jobs');el.innerHTML=`<div class="card"><h3>Operational Tickets</h3><div class="grid three"><input id="jobSearch" placeholder="Search ticket, customer, site, engineer" oninput="renderJobs(document.getElementById('view'))"><select id="jobStatus" onchange="renderJobs(document.getElementById('view'))"><option>All</option>${STATUSES.map(x=>`<option>${x}</option>`).join('')}</select><select id="jobTypeFilter" onchange="renderJobs(document.getElementById('view'))"><option>All</option>${JOB_TYPES.map(x=>`<option>${x}</option>`).join('')}</select></div>${jobTable(filteredJobs())}</div><div id="jobDetail"></div>`}
function findJob(id){return state.jobs.find(j=>j.firestoreId===id||j.ticketId===id)}
function openJob(id){let j=findJob(id);if(!j)return;let systems=j.systems?.length?j.systems:['Other'];let photos=Object.values(j.photos||{});$('jobDetail').innerHTML=`<div class="card"><h2>${esc(j.ticketId||'Ticket Pending')}</h2><p><b>${esc(j.customerName)}</b> / ${esc(j.siteName)}<br>${esc(j.type)} | ${systems.map(s=>`<span class="pill">${esc(s)}</span>`).join(' ')} | <span class="pill ${statusClass(j.status)}">${esc(j.status)}</span></p><p><b>Scope:</b> ${esc(j.scope||'')}</p><label>Work Notes</label><textarea id="notes_${j.firestoreId}">${esc(j.notes||'')}</textarea><label>Customer Remarks</label><textarea id="crem_${j.firestoreId}">${esc(j.customerRemarks||'')}</textarea><button class="btn secondary" onclick="saveJobNotes('${j.firestoreId}')">Save Notes</button><div class="actions">${nextStatusButton(j)}<button class="btn secondary" onclick="shareWhatsApp('${j.firestoreId}')">WhatsApp Report</button><button class="btn secondary" onclick="shareEmail('${j.firestoreId}')">Email Report</button><button class="btn secondary" onclick="printReport('${j.firestoreId}')">Print / PDF</button>${canEditJob(j)?`<button class="btn warn" onclick="editJob('${j.firestoreId}')">Edit</button><button class="btn bad" onclick="deleteJob('${j.firestoreId}')">Delete</button>`:''}</div></div>${renderChecklist(j)}<div class="card"><h3>Photo Evidence</h3><div class="grid two"><div><label>Before / Issue Photo</label><input type="file" accept="image/*" onchange="previewAndAttach('${j.firestoreId}','before',this)"><div id="prev_before_${j.firestoreId}" class="preview"></div></div><div><label>After / Completion Photo</label><input type="file" accept="image/*" onchange="previewAndAttach('${j.firestoreId}','after',this)"><div id="prev_after_${j.firestoreId}" class="preview"></div></div></div><div class="photoGrid">${photos.map(p=>`<div class="photoBox"><img src="${p.dataUrl}" alt="photo"><b>${esc(p.type)}</b><br><span class="muted">${esc(p.by||'')}</span></div>`).join('')||'<p class="muted">No photos uploaded.</p>'}</div></div>`;setTimeout(()=>$('jobDetail').scrollIntoView({behavior:'smooth'}),50)}
function nextStatusButton(j){let next=NEXT_STATUS[j.status];if(!next)return'';if(current.role==='Engineer'&&j.assignedToId!==current.id)return'';return`<button class="btn ok" onclick="advanceJob('${j.firestoreId}','${next}')">Move to ${next}</button>`}
function canEditJob(j){return ['Admin','Coordinator','Supervisor'].includes(current.role)||j.createdById===current.id}
async function updateJob(id,data){data.updatedAt=now();data.updatedBy=current.name;if(cloudReady&&id)await db.collection('jobs').doc(id).set(data,{merge:true});let j=state.jobs.find(x=>x.firestoreId===id);if(j)Object.assign(j,data);saveLocal()}
async function saveJobNotes(id){await updateJob(id,{notes:$('notes_'+id).value,customerRemarks:$('crem_'+id).value});alert('Saved')}
async function advanceJob(id,next){await updateJob(id,{status:next});let j=findJob(id);if(j)await notifyRelevant(j,`${j.ticketId} moved to ${next}`);openJob(id)}
function renderChecklist(j){let systems=j.systems?.length?j.systems:['Other'];return systems.map(sys=>{let currentItems=(j.checklist&&j.checklist[sys])||CHECKLIST_TEMPLATES[sys]?.map(label=>({label,checked:false}))||CHECKLIST_TEMPLATES.Other.map(label=>({label,checked:false}));return`<div class="card"><h3>${esc(sys)} Checklist</h3>${currentItems.map((it,i)=>`<label class="check"><input type="checkbox" ${it.checked?'checked':''} onchange="toggleCheck('${j.firestoreId}','${escAttr(sys)}',${i},this.checked)"> ${esc(it.label||it)}</label>`).join('')}</div>`}).join('')}
function escAttr(s){return String(s).replace(/'/g,'&#39;')}
async function toggleCheck(id,sys,i,checked){let j=findJob(id);let items=(j.checklist&&j.checklist[sys])||CHECKLIST_TEMPLATES[sys].map(label=>({label,checked:false}));items[i].checked=checked;await updateJob(id,{checklist:{...(j.checklist||{}),[sys]:items}})}
async function editJob(id){let j=findJob(id);let site=prompt('Site name',j.siteName);if(site!==null)await updateJob(id,{siteName:site});render()}
async function deleteJob(id){if(!confirm('Delete this job?'))return;if(cloudReady)await db.collection('jobs').doc(id).delete();state.jobs=state.jobs.filter(j=>j.firestoreId!==id);saveLocal();render()}

function renderCreate(el){setTitle('Create Job');let eng=state.users.filter(u=>u.active!==false&&['Engineer','Supervisor'].includes(u.role)).map(u=>`<option value="${u.id}">${esc(u.name)} - ${u.role}</option>`).join('');let custOpts=state.customers.map(c=>`<option value="${esc(c.name)}">`).join('');let siteOpts=state.sites.map(s=>`<option value="${esc(s.name)}">`).join('');el.innerHTML=`<div class="card"><h3>Create Field Job</h3><div class="grid two"><div><label>Customer</label><input id="cj_customer" list="customersList" placeholder="Customer name"><datalist id="customersList">${custOpts}</datalist></div><div><label>Site</label><input id="cj_site" list="sitesList" placeholder="Site / floor / location"><datalist id="sitesList">${siteOpts}</datalist></div></div><div class="grid two"><div><label>Job Type</label><select id="cj_type">${JOB_TYPES.map(x=>`<option>${x}</option>`).join('')}</select></div><div><label>Photo Evidence Policy</label><select id="cj_photo"><option>Optional</option><option>Required</option><option>Not Permitted by Client</option></select></div></div><label>Systems</label><div class="actions">${SYSTEMS.map(s=>`<label class="pill"><input type="checkbox" name="sys" value="${esc(s)}"> ${esc(s)}</label>`).join('')}</div><div class="grid two"><div><label>Assign To</label><select id="cj_eng">${eng}</select></div><div><label>Priority</label><select id="cj_priority"><option>Normal</option><option>High</option><option>Critical</option></select></div></div><label>Scope / Complaint</label><textarea id="cj_scope" placeholder="Brief scope, complaint or PM visit details"></textarea><button class="btn ok full" onclick="createJob()">Create Job</button></div>`}
async function createJob(){let assigned=state.users.find(u=>u.id===$('cj_eng').value)||current;let customer=$('cj_customer').value.trim(),site=$('cj_site').value.trim(),type=$('cj_type').value;if(!customer||!site){alert('Customer and site are required');return}let systems=[...document.querySelectorAll('input[name=sys]:checked')].map(x=>x.value);if(!systems.length)systems=['Other'];let ticketId=newTicket(type==='PM Visit'?'PM':'SRV');let checklist={};systems.forEach(sys=>{checklist[sys]=(CHECKLIST_TEMPLATES[sys]||CHECKLIST_TEMPLATES.Other).map(label=>({label,checked:false}))});let job={ticketId,customerName:customer,siteName:site,type,priority:$('cj_priority').value,systems,assignedToId:assigned.id,assignedToName:assigned.name,createdById:current.id,createdByName:current.name,status:'Assigned',photoPolicy:$('cj_photo').value,scope:$('cj_scope').value,visibleTo:buildVisibleTo(assigned.id),createdAt:now(),updatedAt:now(),photos:{},checklist};if(cloudReady){await db.collection('customers').doc(slug(customer)).set({name:customer,updatedAt:now()},{merge:true});await db.collection('sites').doc(slug(customer+'_'+site)).set({name:site,customerName:customer,updatedAt:now()},{merge:true});let r=await db.collection('jobs').add(job);job.firestoreId=r.id;await notifyRelevant(job,`New ${type} assigned: ${ticketId}`);}else{job.firestoreId=ticketId;state.jobs.unshift(job);saveLocal()}go('jobs')}
async function notifyRelevant(j,msg){if(!cloudReady)return;let toIds=buildVisibleTo(j.assignedToId);await db.collection('notifications').add({title:'Job Update',message:msg,toIds,jobId:j.firestoreId,ticketId:j.ticketId,read:false,createdAt:now()})}
async function previewAndAttach(jobId,type,input){let f=input.files?.[0];if(!f)return;let prev=$(`prev_${type}_${jobId}`);if(prev)prev.innerHTML='<span class="muted">Compressing & uploading...</span>';let dataUrl=await resizeImage(f,1280,.72);if(prev)prev.innerHTML=`<img src="${dataUrl}"><br><b>${esc(f.name)}</b>`;let j=findJob(jobId);let photos={...(j.photos||{}),[type+'_'+Date.now()]:{type,dataUrl,by:current.name,createdAt:now(),fileName:f.name}};await updateJob(jobId,{photos})}
function resizeImage(file,max=1280,q=.72){return new Promise(res=>{let img=new Image(),r=new FileReader();r.onload=e=>{img.onload=()=>{let w=img.width,h=img.height;if(w>max||h>max){let f=Math.min(max/w,max/h);w=Math.round(w*f);h=Math.round(h*f)}let c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);res(c.toDataURL('image/jpeg',q))};img.src=e.target.result};r.readAsDataURL(file)})}
function reportText(j){let checklist=Object.entries(j.checklist||{}).map(([sys,items])=>`\n${sys}:\n`+items.map(i=>`- ${i.checked?'✓':'☐'} ${i.label}`).join('\n')).join('\n');return `PISL FieldOps Report\nTicket: ${j.ticketId}\nCustomer: ${j.customerName}\nSite: ${j.siteName}\nJob Type: ${j.type}\nStatus: ${j.status}\nEngineer: ${j.assignedToName}\nScope: ${j.scope||''}\nWork Notes: ${j.notes||''}\nCustomer Remarks: ${j.customerRemarks||''}\nChecklist:${checklist||' Not updated'}`}
function shareWhatsApp(id){let j=findJob(id);location.href='https://wa.me/?text='+encodeURIComponent(reportText(j))}
function shareEmail(id){let j=findJob(id);location.href='mailto:?subject='+encodeURIComponent('Service Report '+j.ticketId)+'&body='+encodeURIComponent(reportText(j))}
function printReport(id){let j=findJob(id);let photos=Object.values(j.photos||{});let w=window.open('','_blank');w.document.write(`<html><head><title>${esc(j.ticketId)}</title><style>body{font-family:Arial;padding:30px;color:#152033} .top{display:flex;justify-content:space-between;border-bottom:2px solid #153e73;padding-bottom:12px} img.logo{width:125px}.photo{width:220px;margin:8px;border:1px solid #ddd;padding:5px} pre{white-space:pre-wrap;font-family:Arial}</style></head><body><div class="top"><div><h1>Field Service Report</h1><b>Payaswini Integrated Solutions</b></div><img class="logo" src="logo.png"></div><pre>${esc(reportText(j))}</pre><h3>Photo Evidence</h3>${photos.length?photos.map(p=>`<img class="photo" src="${p.dataUrl}">`).join(''):'<p>No photos attached.</p>'}<br><br><p>Engineer Signature: ____________________ &nbsp;&nbsp; Client Signature: ____________________</p></body></html>`);w.document.close();w.print()}

function renderMasters(el){setTitle('Masters');el.innerHTML=`<div class="grid two"><div class="card"><h3>Customer Master</h3><input id="m_customer" placeholder="Customer name"><button class="btn" onclick="addCustomer()">Add Customer</button>${state.customers.map(c=>`<p>• ${esc(c.name)}</p>`).join('')||'<p class="muted">No customers yet.</p>'}</div><div class="card"><h3>Site Master</h3><input id="m_site_customer" placeholder="Customer name"><input id="m_site" placeholder="Site name"><button class="btn" onclick="addSite()">Add Site</button>${state.sites.map(s=>`<p>• ${esc(s.customerName)} - ${esc(s.name)}</p>`).join('')||'<p class="muted">No sites yet.</p>'}</div><div class="card"><h3>Engineer Master</h3>${state.users.filter(u=>u.role==='Engineer'||u.role==='Supervisor').map(u=>`<p>• ${esc(u.name)} - ${esc(u.role)}</p>`).join('')}</div><div class="card"><h3>Checklist Systems</h3>${SYSTEMS.map(s=>`<span class="pill">${esc(s)}</span>`).join(' ')}</div></div>`}
async function addCustomer(){let name=$('m_customer').value.trim();if(!name)return;if(cloudReady)await db.collection('customers').doc(slug(name)).set({name,updatedAt:now()},{merge:true});else state.customers.push({name});saveLocal();render()}
async function addSite(){let customerName=$('m_site_customer').value.trim(),name=$('m_site').value.trim();if(!customerName||!name)return;if(cloudReady)await db.collection('sites').doc(slug(customerName+'_'+name)).set({name,customerName,updatedAt:now()},{merge:true});else state.sites.push({name,customerName});saveLocal();render()}
function renderNotifications(el){setTitle('Notifications');el.innerHTML=`<div class="card"><h3>Notification Center</h3>${state.notifications.map(n=>`<div class="card"><b>${esc(n.title)}</b><p>${esc(n.message)}</p><span class="muted">${esc((n.createdAt||'').replace('T',' ').slice(0,16))}</span><br><button class="btn secondary" onclick="markRead('${n.firestoreId}')">Mark Read</button></div>`).join('')||'<p class="muted">No notifications.</p>'}</div>`}
async function markRead(id){if(cloudReady)await db.collection('notifications').doc(id).set({read:true},{merge:true});let n=state.notifications.find(x=>x.firestoreId===id);if(n)n.read=true;saveLocal();render()}
function renderProposal(el){setTitle('Proposal / Quotation');el.innerHTML='<div class="card"><h3>Proposal Library</h3><p>Proposal / quotation reference retained. Final commercial PDF templates can be attached separately.</p></div>'}
function renderAdmin(el){setTitle('Administration');let vapid=localStorage.getItem(FCM_KEY_LS)||'';el.innerHTML=`<div class="grid two"><div class="card"><h3>Database Maintenance</h3><button class="btn secondary" onclick="backupJson()">Backup JSON</button><button class="btn warn" onclick="purgeOldNotifications()">Clean Read Notifications</button></div><div class="card"><h3>FCM Settings</h3><p class="muted">Firebase project config is unchanged. Paste VAPID key only once per browser to enable device push token registration.</p><input id="adm_vapid" placeholder="FCM Web Push public VAPID key" value="${esc(vapid)}"><button class="btn" onclick="saveVapidKey()">Save VAPID Key</button><button class="btn ok" onclick="enableFCM()">Enable FCM Alerts</button></div><div class="card"><h3>Active Scope</h3><p class="muted">Jobs, realtime updates, FCM alerts, system-wise checklists, service reports, photo uploads, WhatsApp/email sharing, masters, proposal reference.</p><p><b>Not included:</b> Attendance, GPS, QR, SLA, asset history.</p></div></div>`}
function saveVapidKey(){let v=$('adm_vapid').value.trim();if(v)localStorage.setItem(FCM_KEY_LS,v);alert('Saved')}
function backupJson(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pisl-fieldops-backup.json';a.click()}
async function purgeOldNotifications(){if(!confirm('Delete read notifications?'))return;if(cloudReady){let s=await db.collection('notifications').where('read','==',true).get();s.forEach(d=>d.ref.delete())}state.notifications=state.notifications.filter(n=>!n.read);saveLocal();render()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn')?.classList.remove('hidden')});
function installPWA(){if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('installBtn').classList.add('hidden')}else alert('Use browser menu → Add to Home Screen')}
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(console.warn);
window.onload=()=>loadLocal();
