import { getState, getUser, uid, nextTicket, addLog, notify, saveCloud, saveNow, setActiveJobId, customerById, siteById, userById, jobTypes, systems, statuses, isAssigned } from './state.js';
import { esc, getFormData, toast, printHtml } from './utils.js';
import { canAssignJob, canReassignJob, canDeleteJob, canCloseJob, canWorkJob, canViewJob, isEngineer, isViewer } from './permissions.js';
import { reportHtml } from './reports.js';

function userOptions(selected=''){return getState().users.filter(u=>u.active!==false&&u.role!=='Viewer').map(u=>`<option value="${u.id}" ${u.id===selected?'selected':''}>${esc(u.name)} - ${esc(u.role)}</option>`).join('')}
function customerOptions(selected=''){return getState().customers.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>`).join('')}
function siteOptions(selected='',cust=''){return getState().sites.filter(s=>!cust||s.customerId===cust).map(s=>`<option value="${s.id}" ${s.id===selected?'selected':''}>${esc(s.name)}</option>`).join('')}
function statusPill(st){return `<span class="pill ${st==='Closed'?'red':st==='Awaiting Closure'?'amber':'green'}">${esc(st)}</span>`}
function visibleJobs(){return getState().jobs.filter(canViewJob).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''))}
export function renderJobs(){ const rows=visibleJobs().map(j=>`<tr><td><b>${esc(j.ticket)}</b></td><td>${esc(j.customerName)}<br><span class="sub">${esc(j.siteName)}</span></td><td>${esc(j.type)}<br><span class="pill">${esc(j.priority)}</span></td><td>${(j.systems||[]).map(x=>`<span class="pill blue">${esc(x)}</span>`).join('')}</td><td>${statusPill(j.status)}</td><td>${esc(j.assignedName||'-')}</td><td><button class="btn secondary" data-open-job="${j.id}">Open</button></td></tr>`).join('')||`<tr><td colspan="7">No jobs.</td></tr>`;
 return `<div class="card"><div class="toolbar"><h2>Jobs</h2><button class="btn" data-nav="createJob">Create Job</button><button class="btn secondary" id="exportJobsCsv">Export CSV</button></div><table class="table"><thead><tr><th>Ticket</th><th>Client/Site</th><th>Type</th><th>Systems</th><th>Status</th><th>Assigned</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table></div>`}
export function renderCreateJob(job=null){ const edit=!!job; const readonly=isViewer();
 return `<div class="card"><h2>${edit?'Edit Job':'Create Job'}</h2><form id="jobForm" data-id="${job?.id||''}">
 <div class="grid two"><div class="field"><label>Job Type</label><select name="type" required>${jobTypes.map(t=>`<option ${job?.type===t?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label>Priority</label><select name="priority"><option>Low</option><option ${job?.priority==='Medium'?'selected':''}>Medium</option><option ${job?.priority==='High'?'selected':''}>High</option><option ${job?.priority==='Critical'?'selected':''}>Critical</option></select></div></div>
 <div class="grid two"><div class="field"><label>Customer</label><select name="customerId" id="custSel">${customerOptions(job?.customerId)}</select></div><div class="field"><label>Site</label><select name="siteId" id="siteSel">${siteOptions(job?.siteId,job?.customerId)}</select></div></div>
 <div class="field"><label>Systems</label><div class="toolbar">${systems.map(sys=>`<label><input type="checkbox" name="systems" value="${sys}" ${(job?.systems||[]).includes(sys)?'checked':''}> ${sys}</label>`).join('')}</div></div>
 <div class="grid two"><div class="field"><label>Lead / Assigned User</label><select name="assignedTo">${isEngineer()?`<option value="${getUser().id}" selected>${esc(getUser().name)} - Engineer</option>`:userOptions(job?.assignedTo || '')}</select></div><div class="field"><label>Target Date</label><input type="date" name="targetDate" value="${job?.targetDate||''}"></div></div>
 <div class="field"><label>Complaint / Scope / Work Description</label><textarea name="description">${esc(job?.description||'')}</textarea></div>
 <div class="field"><label>Support Users</label><div class="toolbar">${getState().users.filter(u=>u.active!==false&&u.role!=='Viewer').map(u=>`<label><input type="checkbox" name="supportUsers" value="${u.id}" ${(job?.supportUsers||[]).includes(u.id)?'checked':''}> ${esc(u.name)}</label>`).join('')}</div></div>
 <div class="toolbar"><button class="btn">${edit?'Save Changes':'Create Job'}</button>${edit?`<button type="button" class="btn secondary" data-open-job="${job.id}">Cancel</button>`:''}</div></form></div>`}
export function renderJobDetail(id){ const j=getState().jobs.find(x=>x.id===id); if(!j) return `<div class="card"><h2>Job not found</h2><button class="btn secondary" data-nav="jobs">Back</button></div>`; const editable=canAssignJob(j)||j.createdBy===getUser().id; const sys=(j.systems||[]).map(x=>`<span class="pill blue">${esc(x)}</span>`).join('');
 const steps=statuses.map(st=>`<span class="${statuses.indexOf(st)<statuses.indexOf(j.status)?'done':st===j.status?'current':''}">${st}</span>`).join('');
 const actionBtns=renderWorkflowButtons(j); const logs=(j.logs||[]).slice(0,8).map(l=>`<div style="border-left:4px solid #0f4a8a;padding-left:10px;margin:8px 0"><b>${esc(l.stage)}</b><br><span class="sub">${esc(l.displayAt)} • ${esc(l.byName)}</span><br>${esc(l.detail||'')}</div>`).join('');
 return `<div class="toolbar"><button class="btn secondary" data-nav="jobs">← Jobs</button>${editable?`<button class="btn" data-edit-job="${j.id}">Edit / Reassign</button>`:''}<button class="btn secondary" data-print-report="${j.id}">Preview Final Report</button></div>
 <div class="card"><h2>${esc(j.ticket)} ${statusPill(j.status)}</h2><div class="grid two"><div><b>Client/Site:</b> ${esc(j.customerName)} / ${esc(j.siteName)}<br><b>Type:</b> ${esc(j.type)}<br><b>Systems:</b> ${sys}<br><b>Priority:</b> ${esc(j.priority)}</div><div><b>Assigned:</b> ${esc(j.assignedName||'-')}<br><b>Created By:</b> ${esc(j.createdByName||'-')}<br><b>Target:</b> ${esc(j.targetDate||'-')}</div></div><p>${esc(j.description||'')}</p><div class="workflow">${steps}</div><div class="toolbar">${actionBtns}</div></div>
 <div class="grid two"><div class="card"><h2>Work / Report Inputs</h2>${renderWorkForm(j)}</div><div class="card"><h2>Internal Activity</h2>${logs||'No activity yet.'}</div></div>
 <div class="card"><h2>Closure</h2>${renderClosure(j)}</div>`}
function renderWorkflowButtons(j){ if(!canWorkJob(j)) return ''; const next={Assigned:'Accept Job',Accepted:'Start Travel',Traveling:'Check-In', 'Checked-In':'Start Work', Working:'Generate Report Draft','Report Draft':'Mark Report Shared','Report Shared':'Check-Out','Checked-Out':'Move to Awaiting Closure'}; const label=next[j.status]; let btn=label?`<button class="btn" data-flow="${j.id}">${label}</button>`:''; if(canCloseJob(j)&&['Awaiting Closure','Checked-Out'].includes(j.status)) btn+=`<button class="btn green" data-close-job="${j.id}">Close Ticket</button>`; return btn; }
function renderWorkForm(j){ const chk=j.checklist||{}; const material=j.materials||''; return `<form id="workForm" data-id="${j.id}">
 <div class="field"><label>Engineer Observations</label><textarea name="observations">${esc(j.observations||'')}</textarea></div>
 <div class="field"><label>Action Taken / Work Done</label><textarea name="actionTaken">${esc(j.actionTaken||'')}</textarea></div>
 <div class="field"><label>Materials Used</label><textarea name="materials">${esc(material)}</textarea></div>
 <div class="field"><label>Recommendations</label><textarea name="recommendations">${esc(j.recommendations||'')}</textarea></div>
 <div class="field"><label>Customer Remarks / Feedback</label><textarea name="customerRemarks">${esc(j.customerRemarks||'')}</textarea></div>
 <h3>Checklist</h3>${(j.systems||[]).map(sys=>`<div class="card" style="box-shadow:none"><b>${sys}</b>${checkItems(sys).map(it=>`<label style="display:block;margin:8px 0"><input type="checkbox" name="chk_${sys}_${it}" ${chk[sys+'_'+it]?'checked':''}> ${it}</label>`).join('')}</div>`).join('')}
 <button class="btn">Save Report Inputs</button></form>`}
function checkItems(sys){const base={CCTV:['Camera video checked','Recording/playback verified','NVR/HDD health checked','Lens cleaning completed','Network/PoE checked'],ACS:['Reader function checked','Door lock alignment checked','Exit switch/EDR checked','Door closure verified','Software event verified'],FAS:['Panel health checked','Battery/charger checked','Detector sample tested','MCP/sounder sample tested','Fault log reviewed'],PAS:['Amplifier/controller health checked','Microphone checked','Speaker zone tested','Announcement verified'],WLD:['Panel health checked','Sensing cable checked','Alarm tested'], 'Fire Extinguishers':['Pressure gauge checked','Physical condition checked','Expiry/refill date checked'],Networking:['Switch health checked','Patch dressing checked','Link status checked']}; return base[sys]||['Visual inspection completed','Cleaning completed','Functional check completed','Cable dressing verified','Pending issues recorded'];}
function renderClosure(j){ const okReport=!!j.actionTaken, okShared=['Report Shared','Checked-Out','Awaiting Closure','Closed'].includes(j.status), okOut=['Checked-Out','Awaiting Closure','Closed'].includes(j.status); return `<table class="table"><tr><td>Report generated / work action entered</td><td>${okReport?'✅':'❌'}</td></tr><tr><td>Customer remarks / feedback entered</td><td>${j.customerRemarks?'✅':'⚠️'}</td></tr><tr><td>Report shared to customer</td><td>${okShared?'✅':'❌'}</td></tr><tr><td>Check-Out completed (internal only)</td><td>${okOut?'✅':'❌'}</td></tr></table><p class="sub">Customer-facing report excludes Check-In, Check-Out, and internal activity logs.</p>${canDeleteJob(j)?`<div class="danger-zone"><b>Danger Zone</b><br><button class="btn danger" data-delete-job="${j.id}">Delete Job</button></div>`:''}`}
function updateStatus(job,status,detail){job.status=status; addLog(job,status,detail);}
document.addEventListener('click',e=>{ const open=e.target.closest('[data-open-job]'); if(open){setActiveJobId(open.dataset.openJob); window.PISL.render(); return;} const edit=e.target.closest('[data-edit-job]'); if(edit){const j=getState().jobs.find(x=>x.id===edit.dataset.editJob); document.querySelector('.main').innerHTML='<div class="topbar"><h1>Edit Job</h1></div>'+renderCreateJob(j); return;} const del=e.target.closest('[data-delete-job]'); if(del){ if(confirm('Delete this job permanently?')){const s=getState(); const j=s.jobs.find(x=>x.id===del.dataset.deleteJob); s.jobs=s.jobs.filter(x=>x.id!==del.dataset.deleteJob); notify([j.assignedTo,j.createdBy].filter(Boolean),'Job Deleted',`${j.ticket} has been deleted.`,j.id); saveCloud(); setActiveJobId(null); window.PISL.nav('jobs'); toast('Job deleted');} return;} const flow=e.target.closest('[data-flow]'); if(flow){const j=getState().jobs.find(x=>x.id===flow.dataset.flow); const map={Assigned:['Accepted','Accepted by user'],Accepted:['Traveling','Travel started'],Traveling:['Checked-In','Checked-In at site'], 'Checked-In':['Working','Work started'],Working:['Report Draft','Service/Work report draft generated'],'Report Draft':['Report Shared','Report shared to customer through WhatsApp/Email'],'Report Shared':['Checked-Out','Checked-Out after report sharing'],'Checked-Out':['Awaiting Closure','Waiting for superior closure']}; const n=map[j.status]; if(n){updateStatus(j,n[0],n[1]); notify([j.createdBy,j.assignedTo].filter(Boolean),'Job Updated',`${j.ticket}: ${n[0]}`,j.id); saveCloud(); window.PISL.render();} return;} const close=e.target.closest('[data-close-job]'); if(close){const j=getState().jobs.find(x=>x.id===close.dataset.closeJob); if(!canCloseJob(j)){toast('You do not have permission to close this ticket'); return;} updateStatus(j,'Closed','Ticket closed'); notify([j.createdBy,j.assignedTo].filter(Boolean),'Ticket Closed',`${j.ticket} has been closed`,j.id); saveCloud(); window.PISL.render(); return;} const pr=e.target.closest('[data-print-report]'); if(pr){const j=getState().jobs.find(x=>x.id===pr.dataset.printReport); printHtml(reportHtml(j)); }});
document.addEventListener('submit',e=>{ if(e.target.id==='jobForm'){e.preventDefault(); const fd=new FormData(e.target); const id=e.target.dataset.id; const s=getState(); const cust=customerById(fd.get('customerId')), site=siteById(fd.get('siteId')); let systems=[...fd.getAll('systems')]; if(!systems.length) systems=['General']; const assigned=userById(fd.get('assignedTo')); if(id){const j=s.jobs.find(x=>x.id===id); Object.assign(j,{type:fd.get('type'),priority:fd.get('priority'),customerId:cust?.id,customerName:cust?.name,siteId:site?.id,siteName:site?.name,systems,assignedTo:assigned?.id,assignedName:assigned?.name,targetDate:fd.get('targetDate'),description:fd.get('description'),supportUsers:fd.getAll('supportUsers')}); addLog(j,'Job Modified','Job details updated / reassigned'); notify([j.assignedTo,...(j.supportUsers||[])],'Job Updated',`${j.ticket} has been modified/reassigned`,j.id); setActiveJobId(j.id); } else { const u=getUser(); const job={id:uid('job'),ticket:nextTicket(fd.get('type')),type:fd.get('type'),priority:fd.get('priority'),customerId:cust?.id,customerName:cust?.name,siteId:site?.id,siteName:site?.name,systems,assignedTo:assigned?.id,assignedName:assigned?.name,createdBy:u.id,createdByName:u.name,createdAt:new Date().toISOString(),targetDate:fd.get('targetDate'),description:fd.get('description'),supportUsers:fd.getAll('supportUsers'),status:'Assigned',logs:[],checklist:{}}; addLog(job,'Created','Job created'); addLog(job,'Assigned',`Assigned to ${assigned?.name||'-'}`); s.jobs.unshift(job); notify([job.assignedTo,...(job.supportUsers||[])],'New Job Assigned',`${job.ticket} assigned to you`,job.id); setActiveJobId(job.id);} saveCloud(); window.PISL.render(); }
 if(e.target.id==='workForm'){e.preventDefault(); const fd=new FormData(e.target); const j=getState().jobs.find(x=>x.id===e.target.dataset.id); Object.assign(j,{observations:fd.get('observations'),actionTaken:fd.get('actionTaken'),materials:fd.get('materials'),recommendations:fd.get('recommendations'),customerRemarks:fd.get('customerRemarks')}); j.checklist={}; for(const [k,v] of fd.entries()) if(k.startsWith('chk_')) j.checklist[k.replace('chk_','')]=true; addLog(j,'Report Saved','Report inputs/checklist saved'); saveCloud(); toast('Report inputs saved'); window.PISL.render(); }
});
document.addEventListener('change',e=>{ if(e.target.id==='custSel'){const siteSel=document.getElementById('siteSel'); if(siteSel) siteSel.innerHTML=siteOptions('',e.target.value);} });
