import { getState, uid, saveCloud } from './state.js';
import { esc, toast } from './utils.js';
import { canManageMasters } from './permissions.js';
function custOptions(sel=''){return getState().customers.map(c=>`<option value="${c.id}" ${sel===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}
function siteOptions(sel=''){return getState().sites.map(s=>`<option value="${s.id}" ${sel===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}
export function renderMasters(){ if(!canManageMasters()) return '<div class="card">Access denied.</div>'; const s=getState(); return `<div class="grid three"><div class="card"><h2>Customers</h2><form id="customerForm"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Address</label><textarea name="address"></textarea></div><div class="grid two"><div class="field"><label>Contact</label><input name="contact"></div><div class="field"><label>Mobile</label><input name="mobile"></div></div><button class="btn">Add Customer</button></form><table class="table"><tbody>${s.customers.map(c=>`<tr><td>${esc(c.name)}</td><td><button class="btn danger" data-del-cust="${c.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>
 <div class="card"><h2>Sites</h2><form id="siteForm"><div class="field"><label>Customer</label><select name="customerId">${custOptions()}</select></div><div class="field"><label>Site Name</label><input name="name" required></div><div class="field"><label>Address</label><textarea name="address"></textarea></div><button class="btn">Add Site</button></form><table class="table"><tbody>${s.sites.map(x=>`<tr><td>${esc(x.name)}<br><span class="sub">${esc(s.customers.find(c=>c.id===x.customerId)?.name||'')}</span></td><td><button class="btn danger" data-del-site="${x.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>
 <div class="card"><h2>Asset Register</h2><form id="assetForm"><div class="field"><label>Customer</label><select name="customerId">${custOptions()}</select></div><div class="field"><label>Site</label><select name="siteId">${siteOptions()}</select></div><div class="field"><label>System</label><input name="system" required></div><div class="grid two"><div class="field"><label>Asset Name</label><input name="assetName" required></div><div class="field"><label>Qty</label><input name="qty" type="number" value="1"></div></div><div class="grid two"><div class="field"><label>Make</label><input name="make"></div><div class="field"><label>Model</label><input name="model"></div></div><div class="field"><label>Location</label><input name="location"></div><button class="btn">Add Asset</button></form></div></div>
 <div class="card"><h2>Assets</h2><table class="table"><thead><tr><th>Site</th><th>System</th><th>Asset</th><th>Make/Model</th><th>Qty</th><th>Action</th></tr></thead><tbody>${s.assets.map(a=>`<tr><td>${esc(s.sites.find(x=>x.id===a.siteId)?.name||'')}</td><td>${esc(a.system)}</td><td>${esc(a.assetName)}</td><td>${esc(a.make||'')} / ${esc(a.model||'')}</td><td>${esc(a.qty)}</td><td><button class="btn danger" data-del-asset="${a.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>`}
document.addEventListener('submit',e=>{ const s=getState(); if(e.target.id==='customerForm'){e.preventDefault(); const f=new FormData(e.target); s.customers.push({id:uid('cust'),name:f.get('name'),address:f.get('address'),contact:f.get('contact'),mobile:f.get('mobile')}); saveCloud(); window.PISL.render(); toast('Customer added');}
 if(e.target.id==='siteForm'){e.preventDefault(); const f=new FormData(e.target); s.sites.push({id:uid('site'),customerId:f.get('customerId'),name:f.get('name'),address:f.get('address')}); saveCloud(); window.PISL.render(); toast('Site added');}
 if(e.target.id==='assetForm'){e.preventDefault(); const f=new FormData(e.target); s.assets.push({id:uid('asset'),customerId:f.get('customerId'),siteId:f.get('siteId'),system:f.get('system'),assetName:f.get('assetName'),qty:f.get('qty'),make:f.get('make'),model:f.get('model'),location:f.get('location'),status:'Active'}); saveCloud(); window.PISL.render(); toast('Asset added');}});
document.addEventListener('click',e=>{ const map=[['delCust','customers'],['delSite','sites'],['delAsset','assets']]; for(const [ds,key] of map){const b=e.target.closest(`[data-${ds.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())}]`); if(b&&confirm('Delete item?')){const attr='data-'+ds.replace(/[A-Z]/g,m=>'-'+m.toLowerCase()); getState()[key]=getState()[key].filter(x=>x.id!==b.getAttribute(attr)); saveCloud(); window.PISL.render();}} });
