import { getState } from './state.js';
import { esc, shortDate, download, csv } from './utils.js';
import { canViewJob } from './permissions.js';
export function reportHtml(j){ const chk=Object.keys(j.checklist||{}).map(k=>`<tr><td>${esc(k.replaceAll('_',' - '))}</td><td>OK / Done</td></tr>`).join('')||`<tr><td colspan="2">No checklist items marked.</td></tr>`;
 return `<div class="print-sheet"><div class="print-head"><img src="assets/logo.png"><div><h1>Payaswini Integrated Solutions</h1><h2>${esc(j.type)} Report</h2><b>Ticket:</b> ${esc(j.ticket)}</div></div>
 <table class="table"><tr><th>Client</th><td>${esc(j.customerName)}</td><th>Site</th><td>${esc(j.siteName)}</td></tr><tr><th>System(s)</th><td>${esc((j.systems||[]).join(', '))}</td><th>Engineer</th><td>${esc(j.assignedName||'')}</td></tr><tr><th>Job Type</th><td>${esc(j.type)}</td><th>Priority</th><td>${esc(j.priority)}</td></tr></table>
 <h3>Complaint / Scope</h3><p>${esc(j.description||'')}</p><h3>Observations</h3><p>${esc(j.observations||'')}</p><h3>Action Taken / Work Completed</h3><p>${esc(j.actionTaken||'')}</p>
 <h3>Checklist / Check Points</h3><table class="table"><tr><th>Checkpoint</th><th>Status</th></tr>${chk}</table>
 <h3>Materials Used</h3><p>${esc(j.materials||'Nil')}</p><h3>Recommendations</h3><p>${esc(j.recommendations||'Nil')}</p><h3>Customer Remarks / Feedback</h3><p>${esc(j.customerRemarks||'')}</p>
 <div class="grid two"><div class="signature">Engineer Signature</div><div class="signature">Customer / FM Signature</div></div><p class="sub">This customer-facing report excludes internal Check-In, Check-Out, travel and notification logs.</p></div>` }
export function renderReports(){ const jobs=getState().jobs.filter(canViewJob); const rows=jobs.map(j=>`<tr><td>${esc(j.ticket)}</td><td>${esc(j.customerName)} / ${esc(j.siteName)}</td><td>${esc(j.type)}</td><td>${esc(j.status)}</td><td><button class="btn secondary" data-print-report="${j.id}">Preview</button></td></tr>`).join('')||'<tr><td colspan="5">No reports available.</td></tr>'; return `<div class="card"><div class="toolbar"><h2>Reports</h2><button class="btn secondary" id="exportReportsCsv">Export CSV</button></div><table class="table"><thead><tr><th>Ticket</th><th>Client/Site</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table></div>`}
document.addEventListener('click',e=>{ if(e.target.id==='exportReportsCsv'){const rows=[['Ticket','Client','Site','Type','Systems','Status','Action Taken','Recommendations']]; getState().jobs.filter(canViewJob).forEach(j=>rows.push([j.ticket,j.customerName,j.siteName,j.type,(j.systems||[]).join('|'),j.status,j.actionTaken||'',j.recommendations||''])); download('pisl_reports.csv',csv(rows),'text/csv'); }});
